inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 8
    n_positions: 40

training:
    task: noisy_decision_tree
    data: gaussian
    task_kwargs: {"depth":4, "noise_std": 0.05}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 10001
    curriculum:
        dims:
            start: 5
            end: 8
            inc: 1
            interval: 1000
        points:
            start: 11
            end: 40
            inc: 2
            interval: 1000

out_dir: ../models/noisy_decision_tree_std_0.05

wandb:
    name: "noisy_decision_tree_std_1_depth_4"
